### ISSUE TITLE
[Bug]: Mending Repairing

### ISSUE THREAD

**Issue by yorkmouse** [constellation-mc/andromeda#11]
### What happened?

The balanced mending doesn't work as expected. It should let me repair right now correct? 
![2023-06-25_11 26 45](https://github.com/melontini/andromeda/assets/109503749/1493aa04-07fb-4751-be05-4e5e922881bc)
I also checked whether I had it enabled in the config under balanced mending which I changed to true.

### Screenshots

![2023-06-25_11 26 45](https://github.com/melontini/andromeda/assets/109503749/678a46b7-1217-4f1f-bf4b-186aa4c4247e)

### Mod Version

both 1.18.2 and 1.19.3 6.0.0 

### Minecraft Version

- [X] 1.18.2
- [ ] 1.19.x
- [X] 1.19.3

**Comment by zenfyrdev** [comment]
This option only applies to items enchanted with mending, which doesn't appear to be the case here.

**Comment by yorkmouse** [comment]
Then I don't understand the feature, why would people want to repair equipment pieces with high levels of xp if they can just do it very easily with an xp farm when they already have mending? Mending exists just because of that sole reason. Wouldnt it make more sense to be able to repair equipment pieces that don't have mending e.g. items that have enchants that arent compatbile with mending?

**Comment by zenfyrdev** [comment]
Well, this is an opinionated balance tweak for people who think mending is too OP. As per `enchants that arent compatbile with mending`, I might add custom datapack overrides.

**Comment by yorkmouse** [comment]
But how does this make mending less op? Doesn't it make it even more op because now tools have even more features that are enchanted with mending?

**Comment by ImWhiff** [comment]
I think he means that tools with Mending will not be repaired with xp anymore, but instead, it disables the too expensive limit.

**Comment by yorkmouse** [comment]
> I think he means that tools with Mending will not be repaired with xp anymore, but instead, it disables the too expensive limit.

That's what I thought but it's the complete opposite. Only items enchanted with mending can be repaired with xp, normal items will still have the too expensive limit. Just look at my screenshot, it was a vanilla golden hoe, I couldn't repair it anymore.

**Comment by zenfyrdev** [comment]
I don't think I get you.

When this option is on, the "Too Expensive" limit is removed and max repair cost gets bumped to 52. Items will also no longer be repaired by absorbing xp, only using the anvil. Only items enchanted with mending are affected by those tweaks.
