### ISSUE TITLE
[Bug]: Magma Cubes with Wrong Particles

### ISSUE THREAD

**Issue by peow** [constellation-mc/andromeda#113]
### What happened?

the "Slime Slowdown" option inside "Slime Tweaks" is adding Slime particles to the Magma Cube

![image](https://github.com/constellation-mc/andromeda/assets/105888751/b5e0f046-9694-4029-bf12-395eecc409a2)

--------

* Slime Slowdown **disabled**
![2024-04-08_09 26 45](https://github.com/constellation-mc/andromeda/assets/105888751/d131acb9-728f-4541-9e72-fc7ad1dd129e)

* Slime Slowdown **enabled**
![2024-04-08_09 27 38](https://github.com/constellation-mc/andromeda/assets/105888751/456ff1e5-087f-4d29-9114-af7be533d44d)
![2024-04-08_09 27 32](https://github.com/constellation-mc/andromeda/assets/105888751/85f15e9d-53ea-4a2c-b41d-fe12e79745d9)

---------------

particles should be red when touching a Magma Cube

i ask you to make an update to **1.20.1**

### Logs

https://gist.github.com/peow/034e1fa38a5ac2680095b046456f7c97

### Mod Version

1.9.1

### Minecraft Version

Fabric 1.20.1

**Comment by zenfyrdev** [comment]
Should be fixed in latest release.
