### ISSUE TITLE
[Crash]: Latest Andromeda and latest Connector crash on startup

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [constellation-mc/andromeda#116]
### What happened?

I've made a clean instance of connector and Andromeda and the game crashed on startup.

### Logs

https://pastebin.com/4wSfddDj

### Mod Version

1.10.0

### Minecraft Version

1.20.1

**Comment by zenfyrdev** [comment]
Hi, jar transformations are entirely Connector's job and must be reported to them.
