### ISSUE TITLE
[Crash]: Bundle in Item Frame

### ISSUE THREAD

**Issue by yorkmouse** [constellation-mc/andromeda#12]
### What happened?

Crash after putting a bundle in an item frame.

### Logs

[latest.log](https://github.com/melontini/andromeda/files/11859307/latest.log)
is this what you need?

### Mod Version

6.0.0

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [X] 1.19.3

**Comment by zenfyrdev** [comment]
Fixed in 0.7.0
