### ISSUE TITLE
[Crash]: heres some crash with ver.1.11.0 for mc 1.20.1fab

### ISSUE THREAD

**Issue by wrctera** [constellation-mc/andromeda#127]
### What happened?

maybe mixin conflict

### Logs

A mod crashed on startup! net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'andromeda'! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) 	at oolloo.jlw.Wrapper.main(Wrapper.java:51) Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'andromeda'! 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) 	... 6 more Caused by: me.melontini.andromeda.util.exceptions.AndromedaException: (Andromeda) Failed to bootstrap Andromeda! Statuses: {   "platform": "Fabric",   "java_vendor": "Oracle Corporation",   "java_version": "21.0.2",   "bootstrap_status": "SETUP",   "os": "Windows 10",   "environment": "client" } 	at me.melontini.andromeda.util.exceptions.AndromedaException$Builder.build(AndromedaException.java:184) 	at me.melontini.andromeda.base.Bootstrap.onPreLaunch(Bootstrap.java:166) 	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) 	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy33.onPreLaunch(Unknown Source) 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) 	... 7 more Caused by: me.melontini.andromeda.util.exceptions.AndromedaException: (Andromeda) Failed to initialize ModuleManager!!! 	at me.melontini.andromeda.util.exceptions.AndromedaException$Builder.build(AndromedaException.java:184) 	at me.melontini.andromeda.base.Bootstrap.onPreLaunch(Bootstrap.java:155) 	... 10 more Caused by: java.util.concurrent.CompletionException: me.melontini.andromeda.util.exceptions.AndromedaException: (Andromeda) This module requires Commander to be installed! Get it here: https://modrinth.com/project/cmd 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) Caused by: me.melontini.andromeda.util.exceptions.AndromedaException: (Andromeda) This module requires Commander to be installed! Get it here: https://modrinth.com/project/cmd 	at me.melontini.andromeda.util.exceptions.AndromedaException$Builder.build(AndromedaException.java:184) 	at me.melontini.andromeda.util.commander.CommanderSupport.lambda$require$0(CommanderSupport.java:21) 	at me.melontini.dark_matter.impl.base.config.ConfigManagerImpl.lambda$load$2(ConfigManagerImpl.java:71) 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) 	at me.melontini.dark_matter.impl.base.config.ConfigManagerImpl.load(ConfigManagerImpl.java:71) 	at me.melontini.andromeda.base.ModuleManager.lambda$new$7(ModuleManager.java:73) 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) 	... 6 more

### Mod Version

1.11.0

### Minecraft Version

1.20.1fabric

**Comment by wrctera** [comment]
[crash.txt](https://github.com/constellation-mc/andromeda/files/15249148/crash.txt)

**Comment by zenfyrdev** [comment]
Hi, which fabric loader version are you running?

**Comment by zenfyrdev** [comment]
Oh wait, I think I know what's going on. 

If you're using https://modrinth.com/mod/recipe-book-delight, you'll have to remove it as it's no longer supported ([Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated) includes this functionality)

If you're using https://modrinth.com/mod/rbip, update to the latest version.

**Comment by wrctera** [comment]
> Oh wait, I think I know what's going on.
> 
> If you're using https://modrinth.com/mod/recipe-book-delight, you'll have to remove it as it's no longer supported ([Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated) includes this functionality)
> 
> If you're using https://modrinth.com/mod/rbip, update to the latest version.

Thank you so much! it was [recipe-book-delight] that caused the crash!
