### ISSUE TITLE
[Bug]: Zombies may throw air if the item of custom throw behavior doesn't exist

### ISSUE THREAD

**Issue by Rad586** [constellation-mc/andromeda#130]
### What happened?

If the item added in "custom throw behaviors" doesn't exist, and with "zombie can throw items" on, all zombies will try to throw air.
I checked the data of it, there's nothing in its hand.

### Screenshots

![image](https://github.com/constellation-mc/andromeda/assets/99306685/10191a19-f9a8-4856-b21d-c9159f5262f7)

### Mod Version

1.9.0

### Minecraft Version

1.19.2

**Comment by zenfyrdev** [comment]
Could you please check this build? https://github.com/constellation-mc/andromeda/actions/runs/9329162781

It contains all the config changes btw

**Comment by Rad586** [comment]
Yeah, it's fixed.
But seems that somehow the smooth tooltips ignore the config value.

**Comment by zenfyrdev** [comment]
This is fixed in 1.20 & 1.20.4. 1.19.2 will come when I'm brave enough to fix all the git conflicts.
