### ISSUE TITLE
[Bug]: Andromeda causing mod incompatibility

### ISSUE THREAD

**Issue by peow** [constellation-mc/andromeda#132]
### What happened?

I'm using the **EMI** mod to have a recipe/item viewer, but along with it I'm also using the **Legendary Tooltips** mod which makes the tooltips of the items have different styles

**EMI**:
![image](https://github.com/constellation-mc/andromeda/assets/105888751/9e9a59bc-cd7e-4697-aa60-94ac6f312450)

**Legendary Tooltips**:
![image](https://github.com/constellation-mc/andromeda/assets/105888751/5bc79b2c-dd31-4606-9d41-7648ec021082)

these tooltips appear in the inventory but in the EMI menu, tooltips are normal, without the decorations, and EMI causes this on purpose, so as not to have incompatibility problems between the 2 mods

- (EMI+Legendary Tooltips, without Andromeda)

![image](https://github.com/constellation-mc/andromeda/assets/105888751/92eb94ca-c506-4603-837b-10d722db3b0b)

but when using with the **Andromeda** mod, the tooltip decorations reappear in the EMI menu, causing visual glitches

- (EMI+Legendary Tooltips+Andromeda)

![image](https://github.com/constellation-mc/andromeda/assets/105888751/70caa48c-fdef-4dc6-b4c7-72669b9f559b)

*(no visual glitch occurred in this screenshot, but notice that the decorations are showing through)*

![image](https://github.com/constellation-mc/andromeda/assets/105888751/fd6ec4d8-ef9d-4ace-a230-70babd08612d)

*(in this screenshot the line that should be under the name appears a little higher than it should be)*

----------------

- another problem that happens when using the Andromeda mod is that I'm also using the **Tooltipfix** mod, this mod fixes the problem of the Tooltips going off-screen, but Tooltipfix has an incompatibility with EMI, because EMI is configured so that the tooltips always appear on the left side of the mouse, and Tooltipfix ignores this, but what does Andromeda have to do with it? 

Well, since Andromeda shows the decorations of the Tooltips from the Legendary Tooltips mod, it happens that the decorations often appear on the left side of the mouse (because of EMI), but the Tooltip itself appears on the right side (because of Tooltipfix)

![image](https://github.com/constellation-mc/andromeda/assets/105888751/5a34dd5b-d72b-43a0-b581-10952fcf249f)

this doesn't happen **without** Andromeda, because without Andromeda EMI doesn't let the Tooltip decorations be rendered.

![image](https://github.com/constellation-mc/andromeda/assets/105888751/eaa901b0-98d9-4f45-9613-ec2f6490290f)

--------------

I don't think it's relevant, but here's a bit about the incompatibility between Tooltipfix and EMI, but it has nothing to do with Andromeda - https://github.com/kyrptonaught/tooltipfix/issues/30 *(but note that I commented on this Issue thinking that the problem I was experiencing was caused only by the 2 mods, but in fact you also need Andromeda installed)*

I'm using Fabric 1.20.1, Fabric Loader 0.15.11, Fabric API 0.92.1

EMI 1.1.6 (latest version) https://modrinth.com/mod/emi
Legendary Tooltips 1.4.5 + dependencies (latest version) https://modrinth.com/mod/legendary-tooltips
Tooltipfix 1.1.1 (latest version)  https://modrinth.com/mod/tooltipfix
Andromeda 1.12.0 (latest version, but the same happens in previous versions)

I tried disabling Andromeda's settings for tooltips to see if I could fix it, but I **didn't** succeed. I imagine that because Andromeda has some functions for tooltips, it's making them always be fully rendered, even when EMI tries to hide them, but I wouldn't want to have to disable Andromeda's settings for tooltip changes, I really like being able to see the durability of the item in percentage that Andromeda offers

if it's possible to fix this I beg you to publish an update to **1.20.1**, thank you

### Logs

https://mclo.gs/raEiOQj

### Mod Version

1.12.0-1.20.1-build.96

### Minecraft Version

1.20.1

**Comment by zenfyrdev** [comment]
Hi, thank you very much for this very extensive report! I believe this is an issue on iceberg's/Legendary Tooltips' side.

Iceberg has hardcoded checks for Andromeda and it switches rendering logic if it detects the mod. (~Iceberg might not apply TooltipPositioner modifications to decorations, but idk~ actually unrelated)

> I imagine that because Andromeda has some functions for tooltips, it's making them always be fully rendered.

This is not really true, as internally Andromeda completely disables the module. After you restart the game, no events are subscribed to and no mixins are applied.

**Comment by peow** [comment]
i see, when you say "Iceberg has hardcoded checks for Andromeda and it switches rendering logic if it detects the mod", how do you know that?

**Comment by zenfyrdev** [comment]
I decompiled the mod when debugging a different issue.

**Comment by peow** [comment]
ok

**Comment by zenfyrdev** [comment]
I plead innocent until proven guilty. Feel free to reopen if anything changes.

**Comment by Yoni664** [comment]
To fix the problem of tooltipfix mod use adaptativetooltips instead
