### ISSUE TITLE
[Bug]: When the cart is stopped by fabrication&forgery, it will infinitely and rapidly draw fuel from a chest minecart

### ISSUE THREAD

**Issue by MCRusher** [constellation-mc/andromeda#22]
### What happened?

I'm using Quilt 0.19.2 and the only mods are the latest versions (on Modrinth) of Andromeda, Cloth config, Fabrication&Forgery, Linkart, Mod Menu, QFAPI.

I'm using andromeda with fabrication&forgery and linkart as part of a way to make a vanilla+ train system.

I noticed that if I use the andromeda option that allows minecarts to refill when low from nearby chest minecarts, combined with the fabrication&forgery option to toggle off furnace minecarts when they hit inactive powered rails (and reactivate when the rails become active) in order to save fuel, the furnace cart will toggle off and stop moving, but begin draining fuel from the chest minecart very rapidly nonstop till the chest is emptied of fuel.

Would it be possible to make the furnace minecart not consume fuel when not moving or toggled off by another mod?

Also, thanks for making this mod, I originally wanted it for the furnace minecart changes but I also love the auto planting, incubator, etc. since they fit so well in the game as vanilla+ content.

### Mod Version

0.7.0

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, thanks for the report.

This happens because Fabrication sets fuel to 0 every tick the stop conditions are met ([Source](https://github.com/FalsehoodMC/Fabrication/blob/1fcf54f52fefefe4f47ec58f589b7cc684e1d9f7/src/main/java/com/unascribed/fabrication/mixin/e_mechanics/toggleable_furnace_carts/MixinFurnaceMinecartEntity.java#L44C5-L44C5)). I'll try to fix this for the next release.

Glad you're enjoying the mod!

**Comment by zenfyrdev** [comment]
So, this should be fixed in 0.7.1, but I feel the need to tell you that the fix is a bit shaky because I can't access the `fabrication$pauseFuel` field directly. This is a quirk of mixins, but it should work for as long as the field name remains the same.
