### ISSUE TITLE
[Bug]: Andromeda eems to be interfering with Bedrockify's chat tweaks

### ISSUE THREAD

**Issue by vico93** [constellation-mc/andromeda#24]
### What happened?

After installing Andromeda, @juancarloscp52's [Bedrockify](https://github.com/juancarloscp52/BedrockIfy) "Bedrock-like chat" seems to not work anymore. When i press T for a frame the chat is rendered on the style of Bedrock, but right after it reverts to the vanilla style. Can't find any lines on the log that could shed some light about the issue.

I'm pretty sure this issue started after ive installed Andromeda, does this mod do something that can affect the chat?

### Mod Version

0.7.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
You should probably also report this to bedrockify. Currently, Andromeda has no features related to chat HUD rendering.

**Comment by vico93** [comment]
> You should probably also report this to bedrockify. Currently, Andromeda has no features related to chat HUD rendering.

Will do it... strangely when taking out Andromeda from the pack the chat seems to render accordingly to the Bedrock-style chat option of BD is enabled.

**Comment by vico93** [comment]
Done!

**Comment by zenfyrdev** [comment]
Okay, so I looked into the source of dark-matter and there's a bug with tooltip rendering. ([Source](https://github.com/melontini/dark-matter/blob/6611aca35ab8f190c45175b55afd4d6ddec0989f/dark-matter-minecraft/src/main/java/me/melontini/dark_matter/minecraft/client/util/DrawUtil.java#L48C10-L48C10)) The matrices are never popped properly. Not sure how much this this related to this issue.

**Comment by zenfyrdev** [comment]
You can try running Andromeda alongside this version of dark matter https://github.com/melontini/dark-matter/suites/14422042969/artifacts/813638854 (It's an archive with all modules, you need the one without any postfixes)

**Comment by zenfyrdev** [comment]
Any updates? Have you tried the latest version?

**Comment by vico93** [comment]
Strangely it solved itself after a while (i did some updates, maybe it was some other mod interfering with bedrockify.

Sorry to forget to close the issue.
