### ISSUE TITLE
[Bug]: Andromeda & LibZ crash during launch

### ISSUE THREAD

**Issue by DadoIrie** [constellation-mc/andromeda#29]
### What happened?

Andromeda & [LibZ](https://modrinth.com/mod/libz) together are crashing minecraft during launch. Something not working right regarding the config and therefore it crashes client and server during launch.
Luckily the error here points it out pretty accurate the mods which do conflict together and didn't needed to search it manually in my 250+ mod modpack.

### Logs

https://mclo.gs/JWh7YsC

mods not updated in the following log, but it's the server side where it first appeared: https://mclo.gs/0PoHMIn (hope it helps)

### Mod Version

0.8.1 (but also in earlier versions)

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Should be fixed in 0.9.0
