### ISSUE TITLE
[Bug]: Removing mod breaks the world

### ISSUE THREAD

**Issue by Nude-Zenpai** [constellation-mc/andromeda#31]
### What happened?

A bug happened! When i took this mod off my world the entire world broke ,so i was forced to add it back lol like all blocks got confused and turned into different things, my dirt paths all turned to endstone (i havent even gone to the end dimension yet) all my grass turned into mob heads lol , my bamboo turned to coral, ect.

### Mod Version

1.20.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, I need your modlist and config. Just tried with a basic setup + a few performance mods (FerriteCore, LazyDFU, Lithium, Sodium) and everything looks fine.
