### ISSUE TITLE
[Crash]: when looking at itemframetooltip because of currentscreen is null

### ISSUE THREAD

**Issue by DadoIrie** [constellation-mc/andromeda#33]
### What happened?

title says pretty much everything - tested only singleplayer, but I imagine only client crashes when on server since it's a client related issue (can't confirm right now - will do later this afternoon when got time for it)

### Logs

https://mclo.gs/O7GevS4

https://mclo.gs/O7GevS4#L2872 (happens here)

https://mclo.gs/O7GevS4#L2920 (crash report)

### Mod Version

0.7.0 (crash) but happens also with the latest 0.8.1 

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, this should be fixed in the latest iceberg version.

**Comment by DadoIrie** [comment]
will test asap

UPDATE: yes, fixed with updating iceberg
thanks
