### ISSUE TITLE
[Crash]: world creation crash with latest version

### ISSUE THREAD

**Issue by DadoIrie** [constellation-mc/andromeda#34]
### What happened?

crash after a few seconds in the world creation ui
![image](https://github.com/melontini/andromeda/assets/61109153/d69d4dc9-93f0-45d8-b8b9-899635b774a4)

### Logs

https://mclo.gs/F7zSVns

### Mod Version

0.8.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
This should be reported to iceberg. Andromeda is not mentioned in the stacktrace.

**Comment by DadoIrie** [comment]
when removing andromeda & iceberg installed it does not happen and when removing iceberg and leaving andromeda active it does also not happen

so iceberg is the culprit?

updated log with the stack deobfuscator mod: https://mclo.gs/5250GJ4
`java.lang.NullPointerException: Cannot invoke "net.minecraft.client.network.ClientPlayerEntity.getMainHandStack()" because "this.client.player" is null`

**Comment by zenfyrdev** [comment]
I guess iceberg handles tooltips differently when Andromeda is installed. So, yes.

**Comment by DadoIrie** [comment]
still happening and quite some mods depend on iceberg - also appreciating and liking andromeda

strange tho, because why `net.minecraft.client.network.ClientPlayerEntity.getMainHandStack()` is being called in regard to tooltips - might be the held item tooltip?!? what does andromeda do with this one?

**Comment by zenfyrdev** [comment]
Iceberg hasn't been updated to fix this yet, so I'd recommend rolling back to the pre-fixed version of Iceberg and disabling tooltips. (I might disable them automatically with the FeatureManager in 0.9.1).

Iceberg uses different rendering logic when Andromeda is loaded, so it might not have all the checks in place.

The crashing part expects `client.player` not to be null, which is only true if you're playing a world.

There's a check for that in the first part of the code, but it was missed in a later one. (Also, this shouldn't be hardcoded to Andromeda, as the issue stems from `currentScreen` being null)

**Comment by DadoIrie** [comment]
Sadly does not work even after using all the Iceberg versions and disabling tooltips from Andromeda and also with Andromeda's compat mode set to true in order to remove the tooltip mixins leads to the `Cannot read field "width" because "currentScreen" is null` crash which is already fixed in later versions with Iceberg.
Iceberg also not replying on their issue. My modpack & resourcepack is relying on Legendary Tooltips which depends on Iceberg and Andromeda is a really nice addition I'm not removing from the modpack. Literally stuck without a fix from either side - Iceberg or Andromeda

**Comment by zenfyrdev** [comment]
I can't fix this, sadly, as this is an issue on Icebergs side. Btw, the `currentScreen` crash shouldn't happen if you have both `tooltipNotName` and `itemFrameTooltips` off.

**Comment by DadoIrie** [comment]
yeah - my bad - `tooltipNotName` was still active ... all good - thanks for the help

**Comment by AHilyard** [comment]
Sorry for the inconvenience, yes Iceberg handles tooltips differently when Andromeda is installed in order to properly support in-world tooltips with Legendary Tooltips, etc.  I believe I've discovered the cause of this crash and will be releasing an update shortly.
