### ISSUE TITLE
[Bug]: Item frame tooltip glitch

### ISSUE THREAD

**Issue by DadoIrie** [constellation-mc/andromeda#35]
### What happened?

![image](https://github.com/melontini/andromeda/assets/61109153/153156d7-0b54-477d-b694-68b3ada0c1a1)
![image](https://github.com/melontini/andromeda/assets/61109153/d8f0689e-47a7-4392-9afa-ef979c35b3d3)
as you can see on the top left corner of the inventory gui and the esc menu the text is moved there and middle right the tooltip is still present

isn't a bit thingy, but would be nice if that could be fixed ... by simply hiding the tooltip completely when other gui is open

### Mod Version

0.8.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Should be fixed in 0.9.0. Although it looks like a mod incompatibility, since it doesn't happen with Andromeda alone.
