### ISSUE TITLE
[Bug]: World on a server shows different blocks than that they actually are

### ISSUE THREAD

**Issue by j03ri** [constellation-mc/andromeda#42]
### What happened?

Whenever I join a server, doesn't matter which one, the blocks are rendered as different blocks.

### Screenshots

![2023-08-20_13 58 16](https://github.com/melontini/andromeda/assets/16704503/fd3a7c4d-b53d-42b1-97d1-1b8ee117b47e)

### Mod Version

0.9.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, thanks for the report. Are those servers vanilla?

**Comment by j03ri** [comment]
Yes they are, and I have no other mods installed. Also while I'm looking at the mod, the boat with the furnace doesn't float on water.

**Comment by zenfyrdev** [comment]
I believe those issues are caused by a registry de-sync. Can you disable the Incubator, restart and check again?

As per furnace boats: I'll look into it.

**Comment by j03ri** [comment]
It doesn't fix the issue

**Comment by zenfyrdev** [comment]
This is caused by "Cactus Bottle Filling" (`cactusBottleFilling`). It adds a new blockstate to cacti and is required and both client and server. I'll disable it by default in the next update. Thanks, again, for the report.
