### ISSUE TITLE
Spawner Minecarts not functioning

### ISSUE THREAD

**Issue by craisinlord** [constellation-mc/andromeda#45]
I just started an YouTuber SMP using this mod, and we picked up all the spawners with carts thinking we could use them together.

Turns out they are not working at all to spawn anything. As a mod dev myself, I know how disappointing it can be to get a bug report lol

If this could be fixed that'd be great!

Have a good one! 
-Craisin

**Comment by zenfyrdev** [comment]
Hi, thanks for the report. I'm going to move this to the main repo, though.

Anyway, the mod only adds the spawner minecart item and uses the vanilla cart for everything else. 

Mojang might have changed the entity nbt tag between versions, but this shouldn't really be the case, as I remember them working correctly last time I checked it. I'll look into it.

**Comment by zenfyrdev** [comment]
Hello again, I just tested this in Minecraft Revolutions 1.0.1 (Both Andromeda 0.9.0 and 0.9.2), and they work just fine. 

It's worth noting that they abide by the same rules as regular spawners do (Both use the same `MobSpawnerLogic` class), and need to be in the dark to work. 

Oh, also, I recommend updating to 0.9.2 as there was a fix for furnace boats.
