### ISSUE TITLE
[Bug]: The Bamboo Raft with Hopper inventory title says Boat with Hopper

### ISSUE THREAD

**Issue by muhammadrizo-y** [constellation-mc/andromeda#46]
### What happened?

The Bamboo Raft with Hopper inventory title says 'Boat with Hopper'. It should be 'Raft with Hopper'

### Screenshots

![image](https://github.com/melontini/andromeda/assets/87116724/92e4cb02-33ba-4eba-917a-231481c2b8f7)

### Mod Version

v0.9.2-1.20.1

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
This is also an issue with vanilla chest rafts. The name is derived from the entity type which is the same for all boat variants. I'm not sure if there's a good fix for this.
