### ISSUE TITLE
[Bug]: Causing inventory and REI to stop worrking

### ISSUE THREAD

**Issue by BLUEChester** [constellation-mc/andromeda#48]
### What happened?

https://github.com/melontini/andromeda/assets/68225807/95d0f956-7ecd-468d-a86f-4701a86b394c

[latest (1).log](https://github.com/melontini/andromeda/files/12504058/latest.1.log)

Not sure why, just whenever Andromeda is installed it does this

### Mod Version

0.9.2

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, thanks for the report. I can't seem to reproduce this with just Andromeda and REI (+ dependencies).

**Comment by BLUEChester** [comment]
It seems to happen when [TieredZ](https://modrinth.com/mod/tieredz/versions) is installed as well, either if TieredZ or Andromeda are installed it happens.

There's also a full mod list in the latest.log I provided, which could help.

EDIT: I just removed REI, and moved to EMI instead and its working fine now, very weird issue.

**Comment by zenfyrdev** [comment]
Not sure if this is still an issue. Feel free to reopen if it is.
