### ISSUE TITLE
[Bug]: Disconnected by connecting to papermc/spigot server

### ISSUE THREAD

**Issue by some-du6e** [constellation-mc/andromeda#50]
### What happened?

![image](https://github.com/melontini/andromeda/assets/103129948/e40218b9-ef84-4d18-9ee4-44e7920a86d1)
this happens

### Mod Version

0.9.2

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, can you please send me your `latest.log`?

**Comment by zenfyrdev** [comment]
So, I can't seem to reproduce this with a default Paper (181) server and Andromeda (0.9.2) with both default and "everything on" configs. I need more context.

**Comment by some-du6e** [comment]
> So, I can't seem to reproduce this with a default Paper (181) server and Andromeda (0.9.2) with both default and "everything on" configs. I need more context.

Its waterfall > purpur to be clear

log: https://paste.atlauncher.com/view/6b972148-ac88-4c9a-9af3-3052c4f50879
config:https://files.catbox.moe/co9h2h.json

**Comment by zenfyrdev** [comment]
Not sure if this is still an issue. Feel free to reopen if it is.
