### ISSUE TITLE
[Bug]: Crash with The Twilight Forest on Connector

### ISSUE THREAD

**Issue by iludmik** [constellation-mc/andromeda#60]
### What happened?

Not compatible with The Twilight Forest with Sinytra Connector.
Crashes on 1.20.1.

### Logs

https://mclo.gs/vRmPsdq

### Mod Version

Latest and Greatest(Didnt work on all 3 versions for 1.20.1 though)

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
Hi, thanks for the report! This will be fixed in 0.10.0.
