### ISSUE TITLE
[Crash]: Crash on launch

### ISSUE THREAD

**Issue by EthanRStokes** [constellation-mc/andromeda#74]
### What happened?

im not exactly sure, but an exception is thrown from ModuleDiscovery and crashes the game on launch

### Logs

https://mclo.gs/amD6PDg

### Mod Version

1.2.0

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by zenfyrdev** [comment]
> im not exactly sure

I guess that's what I get for ignoring unchecked exceptions.

Well, anyways, I'll look into this, might be something Linux related.

**Comment by EthanRStokes** [comment]
> > im not exactly sure
> 
> I guess that's what I get for ignoring unchecked exceptions.
> 
> Well, anyways, I'll look into this, might be something Linux related.

could be
im currently running ubuntu 23.10

**Comment by zenfyrdev** [comment]
Should be fixed in 1.3.0

**Comment by EthanRStokes** [comment]
yup, works on 1.3.0
