### ISSUE TITLE
[Bug]: Config resetting after every launch

### ISSUE THREAD

**Issue by EthanRStokes** [constellation-mc/andromeda#83]
### What happened?

When saving the config from the Cloth Config GUI, it reverts after a relaunch.

### Screenshots

![image](https://github.com/melontini/andromeda/assets/39657565/1b60e631-ec23-4ab4-9934-06c34efac0a0)

after clicking save & quit and relaunching:
![image](https://github.com/melontini/andromeda/assets/39657565/ba31f888-cb26-482e-bdd7-0dcf4202dd6f)

### Mod Version

1.4.0

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by EthanRStokes** [comment]
update: even changing the config file directly doesnt work
it just gets reset after each launch

**Comment by zenfyrdev** [comment]
Hi, thanks for the report.

Do options from debug.json and mod.json get reset?

**Comment by EthanRStokes** [comment]
> Hi, thanks for the report.
> 
> Do options from debug.json and mod.json get reset?

I dont think so
I believe it happens on specific configs. I know it at least happens on the gui particles config (the one in the screenshot)

**Comment by melontini** [comment]
Strange... I can't seem to reproduce this with just Andromeda. Could you send me your config folder?

**Comment by zenfyrdev** [comment]
Oh wait, I think I know what's going on.

**Comment by zenfyrdev** [comment]
You have to delete the old `andromeda.json` file. I accidentally messed up config loading order after updating DM. 

```java
    public static void onPreLaunch() {
        Config.load(); //We load/create mod.json

        [...]
    
        if (Files.exists(newCfg) && !Files.exists(CommonValues.configPath())) { //We check if mod.json exists - okay
            [...]
        }
    }
```
