### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HuskyInABasket** [constellation-mc/andromeda#89]
### What happened?

may not be a bug but cant seem to upgrade the magnet using heart the sea. I have tried using it with all the crafting tables

### Mod Version

1.4.2

### Minecraft Version

- [ ] 1.18.2
- [X] 1.19.x
- [ ] 1.19.3
- [ ] 1.20.x

**Comment by zenfyrdev** [comment]
Hello, you have to left-click the magnet.

**Comment by HuskyInABasket** [comment]
can you update the wiki on that then? that would be super helpful thanks!
