### ISSUE TITLE
[Crash]: Config related crash on launch.

### ISSUE THREAD

**Issue by Vwriter** [constellation-mc/andromeda#93]
### What happened?

Hello.

The game crashes on launch whenever i change anything in mod's config.
(i tried deleting the config files one-by-one, and every time it crashed still. The game can only launch when no config files are changed from defaults.)

This issue was present since 1.4.2, however, after updating to 1.4.3 it was gone until i installed **HandCrafted 3.0.5**. 

(The same thing also happened when i installed **Better Creepers 1.1**, so i deleted that mod later so i can play normally again. I DONT WANNA DELETE HANDCRAFTED THOUGH xD)

### Logs

https://gist.github.com/Vwriter/98baa2cec3d63e8e50ab990db01233c8

### Mod Version

1.4.3

### Minecraft Version

1.20.1

**Comment by zenfyrdev** [comment]
Hi, thanks for the report! This seems to be a Quilt specific issue. For some reason, the entrypoint I use for loading Andromeda is not equivalent to Fabric. I'll release a patch soon.

**Comment by zenfyrdev** [comment]
Should be fixed in 1.4.4

**Comment by Vwriter** [comment]
Yea thanks!
It works again.
