### ISSUE TITLE
[Bug]: Config Fails To Load On Mod Menu

### ISSUE THREAD

**Issue by karetArts** [constellation-mc/andromeda#99]
### What happened?

Minecraft 1.20.1 , Fabric Loader 0.15.6 , Andromeda 1.6.1 , Fabric API 0.91.0 , Cloth Config 12.0.119

If you need I can give more info
![image](https://github.com/melontini/andromeda/assets/57247411/04471039-2cd1-455b-8daa-58c76c361556)

### Screenshots

![image](https://github.com/melontini/andromeda/assets/57247411/f7f596d8-36a6-4cdd-8b97-3083a6f63c0e)

### Mod Version

1.6.1

### Minecraft Version

1.20.1

**Comment by zenfyrdev** [comment]
Cloth Config 12.x.xxx is for Minecraft 1.20.2. Use 11.1.118
